# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MuensterCityDistrictTools
                                 A QGIS plugin
 Tool to show and export city district informations
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-18
        copyright            : (C) 2026 by Lenja_Jay
        email                : lfipper2@uni-muenster.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MuensterCityDistrictTools class from file MuensterCityDistrictTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MuensterCityDistrictTools import MuensterCityDistrictTools
    return MuensterCityDistrictTools(iface)
