# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lenja\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\muenstercitydistricttools\MuensterCityDistrictTools_export.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pbExportCSV = QtWidgets.QPushButton(Dialog)
        self.pbExportCSV.setObjectName("pbExportCSV")
        self.verticalLayout.addWidget(self.pbExportCSV)
        self.pbExportPDF = QtWidgets.QPushButton(Dialog)
        self.pbExportPDF.setObjectName("pbExportPDF")
        self.verticalLayout.addWidget(self.pbExportPDF)
        self.pbOK = QtWidgets.QPushButton(Dialog)
        self.pbOK.setObjectName("pbOK")
        self.verticalLayout.addWidget(self.pbOK)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Download the info file as ..."))
        self.pbExportCSV.setText(_translate("Dialog", ".csv file"))
        self.pbExportPDF.setText(_translate("Dialog", ".pdf file"))
        self.pbOK.setText(_translate("Dialog", "OK"))