# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lenja\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\muenstercitydistricttools\MuensterCityDistrictTools_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qgis.PyQt.QtWidgets import QDialog 
from PyQt5.QtWidgets import QMessageBox
from qgis.core import QgsProject, QgsProcessingParameterFileDestination
from .MuensterCityDistrictTools_profile import Ui_Dialog
from .MuensterCityDistrictTools_export import Ui_Dialog as Ui_ExportDialog
import csv
from .statistics import createStatistics
from .create_pdf import createPDF



class Ui_MuensterCityDistrictToolsDialogBase(object):
    def setupUi(self, MuensterCityDistrictToolsDialogBase):
        MuensterCityDistrictToolsDialogBase.setObjectName("MuensterCityDistrictToolsDialogBase")
        MuensterCityDistrictToolsDialogBase.resize(415, 297)
        self.verticalLayout = QtWidgets.QVBoxLayout(MuensterCityDistrictToolsDialogBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(MuensterCityDistrictToolsDialogBase)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pbQuery = QtWidgets.QPushButton(MuensterCityDistrictToolsDialogBase)
        self.pbQuery.setObjectName("pbQuery")
        self.verticalLayout.addWidget(self.pbQuery)
        self.pbExport = QtWidgets.QPushButton(MuensterCityDistrictToolsDialogBase)
        self.pbExport.setObjectName("pbExport")
        self.verticalLayout.addWidget(self.pbExport)

        self.retranslateUi(MuensterCityDistrictToolsDialogBase)
        QtCore.QMetaObject.connectSlotsByName(MuensterCityDistrictToolsDialogBase)

    def retranslateUi(self, MuensterCityDistrictToolsDialogBase):
        _translate = QtCore.QCoreApplication.translate
        MuensterCityDistrictToolsDialogBase.setWindowTitle(_translate("MuensterCityDistrictToolsDialogBase", "MuensterCityDistrictTools"))
        self.label.setText(_translate("MuensterCityDistrictToolsDialogBase", "Do you want to get informations about a city district or \n"
"do you want to export informations about a city district?"))
        self.pbQuery.setText(_translate("MuensterCityDistrictToolsDialogBase", "get informations"))
        self.pbExport.setText(_translate("MuensterCityDistrictToolsDialogBase", "export informations"))


class MuensterCityDistrictToolsDialog(QDialog, Ui_MuensterCityDistrictToolsDialogBase):

    def __init__(self, parent=None):
        super(MuensterCityDistrictToolsDialog, self).__init__(parent)
        self.setupUi(self)
        self.pbQuery.clicked.connect(self.open_query_dialog)
        self.pbExport.clicked.connect(self.open_export_dialog)

    ## what happens when you click the query button
    def open_query_dialog(self):
        QMessageBox.information(self, "Information", "Creating statistics...")

        try:
            ## get the layer and the selected Features
            layer = QgsProject.instance().mapLayersByName("Muenster_City_Districts")[0]
            features = layer.selectedFeatures()

            ## check if there is exactly one feature chosen
            if len(features) == 0:
                QMessageBox.warning(None, "Selection", "You have to select a district")
                return
            if len(features) > 1:
                QMessageBox.warning(None, "Selection", "Only one feature can be queried at a time")
                return
        except:
            QMessageBox.critical(None, "Layer Error", "The Layer probably doesn't exist")
        
        ##open the new window
        dialog = QtWidgets.QDialog() # 1. an empty window to host the design
        ui = Ui_Dialog() # 2. an instance of your converted design
        ui.setupUi(dialog) # 3. paint the design onto the window
        
        data = createStatistics(features[0]["NAME"])
    
        # now reach widgets through 'ui.' using their objectNames:
        ui.label.setText(f"City district profile — {data['district_name']}")
        ui.profile_text.setText(
            f"Parent district: {data['parent_district']}\n"
            f"Size: {data['area_km2']} km²\n"
            f"Households: {data['count_houses']}\n"
            f"Parcels: {data['count_parcels']}\n"
            f"Schools: {data['count_schools']}\n"
            f"Pools: {data['count_pools']}"
        )

        ui.pbClose.clicked.connect(dialog.close)
        ## open the window
        dialog.exec_()
            
    ##what happens when you click on the export button
    def open_export_dialog(self):

        ## open a new window
        dialog = QtWidgets.QDialog() # 1. an empty window to host the design
        ui = Ui_ExportDialog() # 2. an instance of your converted design
        ui.setupUi(dialog) # 3. paint the design onto the window

        ## wire the functions to the buttons 
        ui.pbExportCSV.clicked.connect(lambda: self.export_csv())
        ui.pbExportPDF.clicked.connect(lambda: self.export_pdf())
        ui.pbOK.clicked.connect(dialog.close)
        #open the window
        dialog.exec_()
    
    ## function to export the data as csv
    def export_csv(self):
       
        ## get the layer and the selected Features
        layer = QgsProject.instance().mapLayersByName("Muenster_City_Districts")[0]
        features = layer.selectedFeatures()

        ## check if there is exactly one feature chosen
        if len(features) == 0:
            QMessageBox.warning(None, "Selection", "You have to select a district")
            return

        options = QtWidgets.QFileDialog.Options()
        path, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Save CSV", "", "CSV Files (*.csv)", options=options)
        if not path: # user hit Cancel
            QMessageBox.information(None, "Cancelled", "Export was cancelled.")
            return
        
        with open(path, 'w', newline='') as csvfile:
            spamwriter = csv.writer(
                csvfile,
                delimiter=' ',
                quoting=csv.QUOTE_MINIMAL
            )

            spamwriter.writerow(["District Name", "Area (km²)", "Parcels", "Schools"])

            # Loop over layer.selectedFeatures()
            for feature in features:
                data = createStatistics(feature["NAME"])

                spamwriter.writerow([
                    data["district_name"],
                    data["area_km2"],
                    data["count_parcels"],
                    data["count_schools"]
                ])

        QMessageBox.information(None, "Success", "CSV export completed.")


    ## function to export the data as pdf
    def export_pdf(self):
        
        try:
            ## get the layer and the selected Features
            layer = QgsProject.instance().mapLayersByName("Muenster_City_Districts")[0]
            features = layer.selectedFeatures()

            ## check if there is exactly one feature chosen
            if len(features) == 0:
                QMessageBox.warning(None, "Selection", "You have to select a district")
                return
            if len(features) > 1:
                QMessageBox.warning(None, "Selection", "Only one feature can be queried at a time")
                return
        except:
            QMessageBox.critical(None, "Layer Error", "The Layer probably doesn't exist")
        
        pdf_output, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Save PDF", "", "PDF Files (*.pdf)")

        createPDF(self, features[0]["NAME"], pdf_output)
        
        QMessageBox.information(None, "Success", "PDF export completed.")