# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lenja\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\muenstercitydistricttools\MuensterCityDistrictTools_profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.profile_text = QtWidgets.QLabel(Dialog)
        self.profile_text.setText("")
        self.profile_text.setWordWrap(True)
        self.profile_text.setObjectName("profile_text")
        self.verticalLayout.addWidget(self.profile_text)
        self.pbClose = QtWidgets.QPushButton(Dialog)
        self.pbClose.setObjectName("pbClose")
        self.verticalLayout.addWidget(self.pbClose)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "City District Information"))
        self.pbClose.setText(_translate("Dialog", "close"))
